### ISSUE TITLE
Implement mirroring tool 

### ISSUE THREAD

**Issue by edsko** [well-typed/hackage-security#10]
Since the local repo may actually live on a SSH mounted file system:

- [x] Make sure to deal with I/O errors correctly (existing code should already deal with this correctly, and try again _n_ minutes later) -- Left the existing logic in place.
- [x] Make sure to use atomic file operations
- [x] Think about what the repo looks like when one file is changed but updating the next file fails.
- [x] For the `RepoLocal` case, do NOT read the index directly from the local repo (because that would be too slow -- because reading on every poll). Instead keep it in a cache (like we do for remote repos). 
- [x] Still need to _write_ the index to the repo though (**but only on changes**).
- [x] Once we are using `hackage-security` to download stuff from source repo, downloads should be small so can set polling frequency quite high (say, every 5 minutes). -- The polling frequency is not hardcoded into the mirror client, but the _max_ polling frequency is, and was set to 30min. Reduced to 5min.
- [x] Make sure mirroring tool can deal with index containing TUF metadata (currently it tries to mirror each package twice)

**Comment by edsko** [comment]
If we are mirroring to a "smart" server (like Hackage, as opposed to a "dumb" file server) we might have to rethink how we upload packages. The current approach of uploading and subsequently changing upload times will cause the upload times recorded in the index to diverge from the upload times recorded in the packages state. See comments for `mkTarEntry` in `Distribution.Server.Packages.Index` .

**Comment by dcoutts** [comment]
Plan here is to take the existing hackage-mirror tool from the hackage-server repo, replace the bit that downloads from the source server with code that uses the hackage-security lib, and replace the bit that uploads to a dest server with code similar to that in the hackage-security tool that manages local files.
