### ISSUE TITLE
cabal-install should not store 01-index.tar as 00-index.tar

### ISSUE THREAD

**Issue by hvr** [well-typed/hackage-security#117]
in my `index-wayback`-branch I already use a differently named index-filename (as the format differs) to avoid problems when mixing operations with older `cabal`s. The same should be done for 00-index.tar vs 01-index.tar as otherwise we end up with old-`cabal` and new-`cabal` overwriting each other's index-tarballs with their respective format.

(same applies to the index cache, for which I need more meta-data)

**Comment by edsko** [comment]
See discussion in #129.
