### ISSUE TITLE
Merge with cabal HEAD

### ISSUE THREAD

**Issue by edsko** [well-typed/hackage-security#132]
Means we need to decide re bundling new dependencies (tar, hackage-security, etc.).

Need to email cabal-install maintainers.

**Comment by edsko** [comment]
My vote is in favour of not having copies of `tar` and `hackage-security` as part of `cabal-install`. They are big libraries and maintaining a separate copy just seems to incur unnecessary headaches (currently the bundled tar for instance is quite old).

**Comment by 23Skidoo** [comment]
> My vote is in favour of not having copies of `tar` and `hackage-security` as part of `cabal-install`.

+1

**Comment by edsko** [comment]
Relevant PR is https://github.com/haskell/cabal/pull/2983 .
