### ISSUE TITLE
hackage-security broken on Windows?

### ISSUE THREAD

**Issue by edsko** [well-typed/hackage-security#162]
@hvr :

> Did duncan mention to you, that I couldn't get secure repos to work on
> windows? (src-tarball validation fails for some reason)

@dcoutts says something to do with the tar index perhaps?

**Comment by hvr** [comment]
Here's what happens:

```
$ cabal update -v
Selected mirror http://hackage.haskell.org/
Downloading root
Downloading the latest package list from hackage.haskell.org
Selected mirror http://hackage.haskell.org/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Cannot update index (no local copy)
Downloading index
Updating index cache file
C:\Users\hvr\AppData\Roaming\cabal\packages\hackage.haskell.org\00-index.cache
```

```
$ cabal get Win32 -v3
Reading available packages...
Downloading Win32-2.3.1.1...
writing
C:\Users\hvr\AppData\Roaming\cabal\packages\hackage.haskell.org\Win32\2.3.1.1\Win32-2.3.1.1.tar.gz
Selected mirror http://hackage.haskell.org/
Exception Invalid package Win32-2.3.1.1 when using mirror
http://hackage.haskell.org/
Selected mirror http://objects.dreamhost.com/hackage-mirror/
Invalid package Win32-2.3.1.1
```

**Comment by hvr** [comment]
it would be useful to have a bit more debugging output... like e.g. expected vs. observed sha256 sum

**Comment by edsko** [comment]
I think there is no expected length or SHA, because this exception gets thrown if no metadata could be found at all.

**Comment by edsko** [comment]
I wonder if it's something silly like a `/` versus a `\` ...

**Comment by hvr** [comment]
ok... why does it even try to switch mirrors then, if there metadata is missing from 01-index...? It's already known this can only fail, isn't it? :-)

**Comment by edsko** [comment]
*shrugs* general recovery attempt.

**Comment by hvr** [comment]
@edsko if I were to employ printf-style debugging... where would you place the printfs/trace to figure to localise the cause?

**Comment by hvr** [comment]
@edsko your suspicion was spot on:

in the following code:

```
directoryLookup  = liftM dirEntry . Tar.lookup idx . filePath

filePath :: IndexFile dec -> FilePath
filePath = toUnrootedFilePath . unrootPath . indexFileToPath repIndexLayout
```

`filePath` results in a `\`-separated path passed to `Tar.lookup`, and `Tar.lookup` rightfully fails to find the non-existent tar-entry then...

**Comment by dcoutts** [comment]
Ok, so I've made progress but not totally fixed yet.

I've added some tests for the index lookup and made a fix that fixes that test on Windows. See the [pr/index-path-bug](https://github.com/well-typed/hackage-security/tree/pr/index-path-bug) branch.

But with cabal itself, that only gets us from here:

```
cabal new-build --dry
Invalid package HTTP-4000.3.3
```
to
cabal.exe new-build --dry
Resolving dependencies...
<repo>/package\HTTP-4000.3.3.tar.gz not found in corresponding target metadata
```

Almost certainly this is again due to a mismatch between `package\HTTP-4000.3.3.tar.gz` and `package/HTTP-4000.3.3.tar.gz`.

The fundamental problem here is that our `Path` type uses the native `FilePath` convention, but sometimes we need a specific convention, like POSIX for the tar index, and indeed also for files listed in metadata files.

My first patch (apart from the test) is not a comprehensive solution at all, it just adds a conversion. I initially started on a more comprehensive solution where we used the root type to determine if the path should follow native of posix file conventions. The problem with this approach is that it doesn't help for unrooted paths, which is just a single type. I'm tempted to try again but make the Path type [String] rather than FilePath and use the appropriate conversion when converting from a rooted path back to a FilePath or other stringy path kind.

@edsko what do you reckon?

**Comment by dcoutts** [comment]
Fixed I think.
