### ISSUE TITLE
build fails with ghc-7.10+

### ISSUE THREAD

**Issue by michaelt** [well-typed/hackage-security#83]
I don't have ghc-7.10.2 yet but the new 'Checked.hs' fails with 7.10.1 and a version of head from a couple weeks ago. 

    src/Hackage/Security/Util/Checked.hs:27:21: error:
        Could not deduce (Exception e0)
        from the context: Exception e
          bound by the type signature for:
                   rethrowUnchecked :: Exception e => (Throws e => IO a) -> IO a
          at src/Hackage/Security/Util/Checked.hs:27:21-75
        The type variable ‘e0’ is ambiguous
        In the ambiguity check for the type signature for ‘rethrowUnchecked’:
          rethrowUnchecked :: forall e a.
                              (Throws e => IO a) -> Exception e => IO a
        To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
        In the type signature for ‘rethrowUnchecked’:
          rethrowUnchecked :: forall e a.
                              (Throws e => IO a) -> (Exception e => IO a)

    src/Hackage/Security/Util/Checked.hs:27:21: error:
        Could not deduce (Throws e)
        from the context: Exception e
          bound by the type signature for:
                   rethrowUnchecked :: Exception e => (Throws e => IO a) -> IO a
          at src/Hackage/Security/Util/Checked.hs:27:21-75 
          ...

I tried the obvious expedient of newtype wrapping, but it still needed AllowAmbiguousTypes

    newtype T e a = T (Throws e => IO a)

    -- | Rethrow checked exceptions as unchecked (regular) exceptions
    rethrowUnchecked :: forall e a. (Throws e => IO a) -> (Exception e => IO a)
    rethrowUnchecked act = aux (T act) throwIO
      where
      aux :: T e a -> (e -> IO a) -> IO a
      aux = unsafeCoerce

    -- | Catch a checked exception
    --
    -- This is the only way to discharge a 'Throws' type class constraint.
    catchChecked :: Exception e => (Throws e => IO a) -> (e -> IO a) -> IO a
    catchChecked io f = catchHelper (T io) f 

    catchHelper :: Exception e => T e a -> (e -> IO a) -> IO a
    catchHelper io g = catch (aux io throwIO) g 
     where
      aux :: T e a -> (e -> IO a) -> IO a
      aux = unsafeCoerce 
  
    -- | 'catchChecked' with the arguments reversed
    handleChecked :: Exception e => (e -> IO a) -> (Throws e => IO a) -> IO a
    handleChecked f io = flip catchHelper f (T io)

**Comment by edsko** [comment]
Ah, interesting! I hadn't had the chance yet to test with 7.10. Thanks for the report, will look into this.

**Comment by edsko** [comment]
I ended up using a workaround a bit like yours, but managed to keep it internal to `rethrowUnchecked` so that the external API is unchanged. Thanks for the report!

**Comment by michaelt** [comment]
I see, the comment on `Wrap` makes it clearer what's going on.
